version: '3.9'

networks:
  app-crud-network:
    driver: bridge

services:

  # ASP.NET Core Web API Application
  crud-api:
    image: ${DOCKER_REGISTRY-}crud-api
    container_name: crud-api
    restart: always
    build:
      context: .
      dockerfile: '01 - Presentation/API/WebAPI/Dockerfile'
    expose:
      - 5072
    ports:
      - 5072:5072
    links:
      - sqlserver
      - rabbitmq
      - mongoserver
    networks:
      - app-crud-network
    depends_on:
      - sqlserver
      - mysql
      - postgres
      - rabbitmq
      - mongoserver
      - kafdrop
      - kafka
    environment:
      ConnectionStrings__SqlConnection: "Server=sqlserver;Integrated Security=true;Initial Catalog=CrudDDDDotNetNet7;User Id=sa;Password=@C23l10a1985;Trusted_Connection=false;MultipleActiveResultSets=true;Encrypt=True;TrustServerCertificate=True;"
  
  # SQL Server
  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge:latest
    cap_add: [ 'SYS_PTRACE' ]
    hostname: mssql
    container_name: sqlserver
    restart: always
    expose:
      - 1433
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: "@C23l10a1985"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    networks:
      - app-crud-network

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: C23l10a1985
      MYSQL_USER: gfmaurila
      MYSQL_PASSWORD: C23l10a1985
      MYSQL_DATABASE: gfmaurila
    restart: always
    expose:
      - 3306
    ports:
      - "3306:3306"
    networks:
      - app-crud-network

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: gfmaurila
      POSTGRES_PASSWORD: C23l10a1985
      POSTGRES_DB: gfmaurila
    restart: always
    expose:
      - 5432
    ports:
      - "5432:5432"
    networks:
      - app-crud-network

  # Mongo Server
  mongoserver:
    image: mongo:latest
    container_name: mongoserver
    restart: always
    expose:
      - 27017
    ports:
      - 27017:27017
    networks:
      - app-crud-network

  # Redis Cache Server
  redis:
    image: redis:latest
    container_name: redis
    command: redis-server --requirepass C23l10a1985
    restart: always
    expose:
      - 6379
    ports:
      - 6379:6379
    networks:
      - app-crud-network
  
  # http://localhost:15672
  # usuário guest 
  # senha guest
  # Rabbit MQ
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    restart: always
    expose:
      - 15672
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - app-crud-network

  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "always"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:29092"
      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
    depends_on:
      - "kafka"
    networks:
      - app-crud-network

  kafka:
    image: obsidiandynamics/kafka
    restart: "always"
    ports:
      - "2181:2181"
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: "INTERNAL://:29092,EXTERNAL://:9092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:29092,EXTERNAL://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT: "6000"
      KAFKA_RESTART_ATTEMPTS: "10"
      KAFKA_RESTART_DELAY: "5"
      ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL: "0"
    networks:
      - app-crud-network

  
